CREATE DATABASE IF NOT EXISTS codeup_test_db;
USE codeup_test_db;

CREATE TABLE IF NOT EXISTS cats
(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    middle_name VARCHAR(255),
    PRIMARY KEY (id)
);

SHOW TABLES;

DESCRIBE cats;

DROP TABLE IF EXISTS cats;